article page display
g-kimani/nc-news pull request #3
Opened 2023-05-30 15:13 UTC by g-kimani

2023-05-30 15:38 UTC, MKD01 requested changes
This pull request has two tickets combined into one. Double check your trello board tickets and use this as a guide for each pull request. 

Please split these two tickets up and send them through as separate pr requests.

2023-05-30 15:38 UTC, MKD01 commented on src/components/ArticlePage.jsx
> +      <ArticleComments article_id={article_id} />
This ticket should not include comments

2023-05-30 15:41 UTC, g-kimani commented on src/components/ArticlePage.jsx
> +      <ArticleComments article_id={article_id} />
Okay no problem

2023-05-31 08:52 UTC, Keb84 approved these changes
Great work for ticket 5. Ready to merge 🙂

2023-05-31 08:58 UTC, merged